### ISSUE TITLE
[iPhone] Everytime Rebooting

### ISSUE THREAD

**Issue by Biker1Ben** [miathedev/KomootBLEConnect#1]
I have the problem, that my esp32 shows a connection to my IPhone but directly after that it's rebooting. I'm using your example code, can you help me?

Rebooting...
15:47:33.347 -> ets Jun  8 2016 00:22:57
15:47:33.347 -> 
15:47:33.347 -> rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
15:47:33.347 -> configsip: 0, SPIWP:0xee
15:47:33.347 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
15:47:33.347 -> mode:DIO, clock div:1
15:47:33.347 -> load:0x3fff0030,len:1184
15:47:33.347 -> load:0x40078000,len:12804
15:47:33.347 -> ho 0 tail 12 room 4
15:47:33.347 -> load:0x40080400,len:3032
15:47:33.347 -> entry 0x400805e4
15:47:33.674 -> Komoot Simple Example
15:47:34.421 -> Scanning!
15:47:34.421 -> BLE Advertised Device found: Name: Benjamins iPhone, Address: 76:80:b2:e9:5e:65, serviceUUID: 71c1e128-d92f-4fa8-a2b2-0f171db3436c, txPower: 12
15:47:34.468 -> Found possile candidate
15:47:34.607 -> BLE Advertised Device found: Name: , Address: 09:54:b6:b0:a6:2d, serviceUUID: 0000fd6f-0000-1000-8000-00805f9b34fb
15:47:37.344 -> BLE Advertised Device found: Name: , Address: f2:f9:74:fc:a4:a3, manufacturer data: 4c0012020000
15:47:39.437 -> Forming a connection to 76:80:b2:e9:5e:65
15:47:39.528 -> Connection done
15:47:39.528 -> Trying to connect to serviceGuru Meditation Error: Core  0 panic'ed (Unhandled debug exception). 
15:47:41.390 -> Debug exception reason: Stack canary watchpoint triggered (BTU_TASK) 
15:47:41.390 -> Core  0 register dump:
15:47:41.390 -> PC      : 0x40083436  PS      : 0x00060236  A0      : 0x80083555  A1      : 0x3ffcffa0  
15:47:41.390 -> A2      : 0x00000268  A3      : 0x00001400  A4      : 0x00000000  A5      : 0x00000000  
15:47:41.390 -> A6      : 0x00001004  A7      : 0x3ffb6c20  A8      : 0x3ffd0630  A9      : 0x3ffd05c0  
15:47:41.390 -> A10     : 0x3ffb6c20  A11     : 0x3ffda564  A12     : 0x3ffb6388  A13     : 0x00000000  
15:47:41.390 -> A14     : 0x00000000  A15     : 0x3ffdbc6c  SAR     : 0x00000010  EXCCAUSE: 0x00000001  
15:47:41.436 -> EXCVADDR: 0x00000000  LBEG    : 0x4008fc84  LEND    : 0x4008fc9a  LCOUNT  : 0xffffffff  
15:47:41.436 -> 
15:47:41.436 -> 
15:47:41.436 -> Backtrace:0x40083433:0x3ffcffa00x40083552:0x3ffcffd0 0x4010df43:0x3ffd0020 0x400e71a9:0x3ffd0050 0x40113cec:0x3ffd0080 0x4013655b:0x3ffd0310 0x40114c9e:0x3ffd05a0 0x40136131:0x3ffd05c0 0x40114c9e:0x3ffd0630 0x40135d9e:0x3ffd0650 0x40113ffd:0x3ffd0670 0x40114069:0x3ffd0900 0x401141a6:0x3ffd0920 0x400feff9:0x3ffd0940 0x400fa366:0x3ffd0be0 0x400fa811:0x3ffd0e70 0x400fb1c9:0x3ffd0ed0 0x400fc504:0x3ffd0f10 0x400fc53a:0x3ffd0f30 0x40107795:0x3ffd0f50 0x400f8320:0x3ffd10e0 0x40110e27:0x3ffd1100 
15:47:41.483 -> 
15:47:41.483 -> 
15:47:41.483 -> 
15:47:41.483 -> 
15:47:41.483 -> ELF file SHA256: 0000000000000000
15:47:41.483 -> 
15:47:41.483 -> Rebooting...

**Comment by miathedev** [comment]
Sure, please provide me the complete code you have written.

**Comment by Biker1Ben** [comment]
#include <Arduino.h>
#include <KomootBLEConnect.h>
#include "BLEDevice.h"

Komoot komoot;

void setup() {
    Serial.begin(115200);
    Serial.println("Komoot Simple Example");

    komoot.begin("BLEDEV");
}

void loop() {
    komoot.loop();
    if(komoot.isConnected()){
        KomootPayloadContainer dataSet = komoot.getDataSet();
        Serial.println(dataSet.street);
    }
}


That's all, I just wanted to see if I can get Navigation task in the serial plotter in arduino IDE. All that I got is in my first post

**Comment by miathedev** [comment]
I have to dig into it a little bit further.
Maybe there have been API changes somewhere.

Ill get back to you. I want you to know i cant do it this week because of the lack of hardware.

**Comment by miathedev** [comment]
I dont know how familiar you are with my code. But at least i know it failed with connecting to the service itself:
`pRemoteService = pClient->getService(serviceUUID);`
This must be the line where it crashed.

**Comment by Joshicopter** [comment]
Do you know a solution for this?
Unfortunately I have the problem with all Komoot codes and can‘t find a solution.

**Comment by miathedev** [comment]
Ok? @Joshicopter do you use an iPhone too? What device do you use? (Company, Type, System Version)

Yet i didnt manage to get someone who is willing to borrow me an iPhone.

**Comment by miathedev** [comment]
Sorry, didnt want it to close.

**Comment by Biker1Ben** [comment]
Sorry for being away for such a long  time.
I found a solution with another repository and code and the komoot navigation is partially working. I only have a problem with displaying the correct navigation symbols, it will always show the same symbols. I suspect the outdated code behind it, maybe anybody could help me with this?

**Comment by miathedev** [comment]
Please discuss this issue on the other repository which code you are using.
